---
- name: Generate ISOs for the workers
  include_role:
    name: "{{ playbook_dir }}/../common-roles/download-iso"
  vars:
    cluster_name_var: "{{ cluster_name }}-day2"
    minimal: True
    final_iso_path_var: "{{ final_iso_path }}"
