---
- name: Configure cluster
  block:
    - name: Update hostnames
      shell: "IP=$(aicli list hosts | grep {{ cluster_name }}-day2 | grep {{ hostvars[item].ip }} | cut -d '|' -f 4 | tr -d ' '); aicli update host $IP -P name={{ hostvars[item].hostname }}"
      when: hostvars[item].hostname is defined and hostvars[item].hostname|length > 0 
      with_items: "{{ groups['worker_nodes'] }}"

    - name: For each worker, override the default mcp if it has a profile
      shell: "IP=$(aicli list hosts | grep {{ cluster_name }}-day2 | grep {{ hostvars[item].hostname }} | cut -d '|' -f 4 | tr -d ' '); aicli update host $IP -P mcp={{ hostvars[item].profile }}"
      when: hostvars[item].profile is defined and hostvars[item].profile|length > 0 and hostvars[item].hostname is defined and hostvars[item].hostname|length > 0
      with_items: "{{ groups['worker_nodes'] }}"

    - name: Install cluster
      shell: "aicli start cluster {{ cluster_name }}-day2"
  environment:
    AI_URL: "{{ ai_url }}"

