---
- name: Install needed packages
  yum:
    name:
      - python3-pip
      - openssl-devel
      - make
      - podman
      - skopeo
      - jq
      - git
    state: present

- name: Create temporary directory
  tempfile:
    state: directory
  register: temporary_directory

- name: Install golang
  ansible.builtin.shell:
    cmd: "{{ item }}"
  with_items:
    - "curl {{ golang_url | default('https://dl.google.com/go/go1.13.6.linux-amd64.tar.gz') }} -o {{ temporary_directory.path }}/go.tar.gz"
    - "tar -zxvf {{ temporary_directory.path }}/go.tar.gz -C /usr/local/"
    - "echo 'export GOROOT=/usr/local/go' | tee -a /etc/profile"
    - "echo 'export PATH=$PATH:/usr/local/go/bin' | tee -a /etc/profile"

- name: Install grpcurl
  ansible.builtin.shell:
    cmd: "{{ item }}"
  with_items:
    - "curl -L https://github.com/fullstorydev/grpcurl/releases/download/v1.8.0/grpcurl_1.8.0_linux_x86_64.tar.gz -o {{ temporary_directory.path }}/grpcurl.tar.gz"
    - "tar -zxvf {{ temporary_directory.path }}/grpcurl.tar.gz -C /usr/local/"

- name: install httpd
  include_role:
    name: "{{ playbook_dir }}/../common-roles/install-httpd"
  when: virtualmedia_over_http is defined and virtualmedia_over_http|bool == True

- name: install racadm
  include_role:
    name: "{{ playbook_dir }}/../common-roles/install-racadm"
  when: need_racadm|bool == True

- name: Install provisioner cluster
  include_role:
    name: "{{ playbook_dir }}/../common-roles/create-provisioner-cluster"
  when: provisioner_cluster_name is defined and provisioner_cluster_name|length > 0 
