- name: Copy local kubeconfig to remote server if set
  ansible.builtin.copy:
    src: "{{ provisioner_cluster_kubeconfig }}"
    dest: "{{ temporary_path }}/kubeconfig"

- name: Get IP of master nodes
  ansible.builtin.shell:
    cmd: oc get nodes  -o jsonpath='{ $.items[*].status.addresses[?(@.type=="InternalIP")].address }' | tr " " "\n"
  register: master_nodes
  environment:
    KUBECONFIG: "{{ temporary_path }}/kubeconfig"

- name: Create tmp directory for haproxy
  tempfile:
    state: directory
  register: tempdiroutput

- name: Copy template to temporary directory
  template:
    src: "./templates/create_haproxy.sh.j2"
    dest: "{{ tempdiroutput.path }}/create_haproxy.sh"
    mode: 0755
  vars:
    master_ips: "{{ master_nodes.stdout_lines }}"

- name: Install haproxy
  ansible.builtin.shell:
    cmd: "bash {{ tempdiroutput.path }}/create_haproxy.sh"
