- name: Clone the assisted installer project
  git:
    repo: 'https://github.com/openshift/assisted-service'
    dest: /opt/assisted-service-ztp
    update: yes
    force: yes

- name: Add env var to file if does not exist
  lineinfile:
    path: /opt/assisted-service-ztp/onprem-environment
    line: "{{ item }}"
  with_items: "{{ onprem_vars }}"

- name: Clean the pod
  shell: "podman pod rm -f assisted-installer"
  ignore_errors: yes

- name: Read json with image versions
  shell: cat "/opt/assisted-service-ztp/default_ocp_versions.json"
  register: json_content
  when: rhcos_base_iso is not defined or rhcos_base_iso|length == 0

- name: Query for the right ISO according to the version
  vars:
    jsondata: "{{ json_content.stdout | from_json }}"
    query_version: "\"{{ cluster_version }}\".rhcos_image"
  set_fact:
    rhcos_base_iso: "{{ jsondata | json_query(query_version) }}"
  when: rhcos_base_iso is not defined or rhcos_base_iso|length == 0

- name: Get RHCOS livecd iso
  shell: "curl {{ rhcos_base_iso }} -o livecd.iso"
  args:
    chdir: "/opt/assisted-service-ztp"

- name: Start the assisted installer service
  shell: "make deploy-onprem"
  args:
    chdir: "/opt/assisted-service-ztp"
  environment:
    RHCOS_BASE_ISO: "{{ rhcos_base_iso }}"
