---
- name: create cluster
  include_role:
    name: "{{ playbook_dir }}/../common-roles/create-cluster"
  vars:
    extra_args: "-P ingress_vip={{ ingress_vip }}"
    cluster_name_var: "{{ cluster_name }}"

- name: download ISO
  include_role:
    name: "{{ playbook_dir }}/../common-roles/download-iso"
  vars:
    cluster_name_var: "{{ cluster_name }}"
    final_iso_path_var: "{{ temporary_path }}"
