- name: Check if the node is already enrolled
  shell: "aicli list hosts | grep {{ item }} | wc -l"
  register: host_exist
  environment:
    AI_URL: "{{ ai_url }}"

- name: Delete host if it is a redeploy
  shell: "aicli delete host {{ item }}"
  when: host_exist.stdout|int == 1 and hostvars[item].redeploy|bool == true

- name: Enroll a SuperMicro node
  include_role:
    name: "{{ playbook_dir }}/../common-roles/enroll-supermicro"
  vars:
    iso_name: "{{ cluster_name }}-day2.iso"
    smb_host: "{{ hostvars[item].smb_host }}"
    smb_path: "{{ hostvars[item].smb_path }}"
    bmc_address: "{{ hostvars[item].bmc_address }}"
    bmc_user: "{{ hostvars[item].bmc_user }}"
    bmc_password: "{{ hostvars[item].bmc_password }}"
  when: hostvars[item].bmc_type == "SuperMicro" and (host_exist.stdout|int == 0 or hostvars[item].redeploy|bool == true)

- name: Enroll a Dell node
  include_role:
    name: "{{ playbook_dir }}/../common-roles/enroll-dell"
  vars:
    iso_name: "{{ cluster_name }}-day2.iso"
    bmc_user: "{{ hostvars[item].bmc_user }}"
    bmc_password: "{{ hostvars[item].bmc_password }}"
    bmc_address: "{{ hostvars[item].bmc_address }}"
    iso_url: "{{ hostvars[item].iso_url }}"
  when: hostvars[item].bmc_type == "Dell"  and (host_exist.stdout|int == 0 or hostvars[item].redeploy|bool == true)
