---
- name: Enroll remote worker if needed
  include_tasks: add_remote_worker.yaml
  loop: "{{ groups['worker_nodes'] }}"

- name: Wait until hosts are ready in Assisted Installer
  shell: "aicli list hosts | grep {{ cluster_name }}-day2 | grep 'insufficient\\|known\\|added-to-existing-cluster' | wc -l"
  register: hosts_ready
  until: hosts_ready.stdout|int == groups['worker_nodes'] | length
  retries: 100
  delay: 30
  environment:
    AI_URL: "{{ ai_url }}"
