- name: mirror assisted installer images
  include_role:
    name: "{{ playbook_dir }}/../common-roles/mirror-ai-images"

- name: Download image to temporary directory
  uri:
    url: "{{ item }}"
    dest: "{{ http_server_path | default('/var/www/html/') }}/{{ item | basename }}"
    creates: "{{ http_server_path | default('/var/www/html/') }}/{{ item | basename }}"
  with_items:
  - "{{ rhcos_remote_iso }}"
  - "{{ rhcos_remote_rootfs }}"
  delegate_to: "{{ groups['http_mirror'][0] }}"
