---
- name: Install needed packages
  yum:
    name:
      - podman
      - openssl-devel
      - make
      - libvirt-python3
    state: present

- name: install racadm
  include_role:
    name: "{{ playbook_dir }}/../common-roles/install-racadm"
  when: need_racadm|bool == True

- name: install aicli
  include_role:
    name: "{{ playbook_dir }}/../common-roles/install-aicli"

- name: Read json with image versions
  shell: cat "/opt/assisted-service-ztp/default_ocp_versions.json"
  register: json_content

- name: Query for the right ISO according to the version
  vars:
    jsondata: "{{ json_content.stdout | from_json }}"
    query_version: "\"{{ cluster_version }}\".rhcos_image"
  set_fact:
    rhcos_base_iso: "{{ jsondata | json_query(query_version) }}"

- name: install assisted installer
  include_role:
    name: "{{ playbook_dir }}/../common-roles/install-assisted-installer"
  vars:
    onprem_vars:
      - - "SUPPORT_L2=false"
        - "SERVICE_BASE_URL={{ ai_url }}"
        - "HW_VALIDATOR_MIN_DISK_SIZE_GIB=50"
        - "PUBLIC_CONTAINER_REGISTRIES=quay.io,registry.svc.ci.openshift.org"
        - "RHCOS_BASE_ISO={{ rhcos_base_iso }}"
        - "AUTH_TYPE=none"

