---
- name: create day 2 cluster
  include_role:
    name: "{{ playbook_dir }}/../common-roles/create-cluster"
  vars:
    extra_args: "-P ingress_vip={{ ingress_vip }}"
    cluster_name_var: "{{ cluster_name }}-day2"
